spring:
  profiles:
      active: native
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id : discovery-service
          uri: http://localhost:8671
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway-Request,true
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
    config:
      enabled: false

  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
server:
  port: 8090

