services:
  keycloak-db:
    image: postgres:17-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    restart: unless-stopped
  keycloak-server:
    image: quay.io/keycloak/keycloak
    container_name: keycloak-server
    ports:
      - "9090:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    command:
      - start-dev
      - --import-realm

    volumes:
      - ./import:/opt/keycloak/data/import:ro
    restart: unless-stopped

volumes:
  keycloak-data: