services:
  ticket-db:
    image: postgres:17.5-alpine
    container_name: ticket-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ticket-db-data:/var/lib/postgresql/data

  ticket-adminer:
    image: adminer:4.8.1
    container_name: ticket-adminer
    restart: always
    ports:
      - "8088:8080"

  ticket-keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: ticket-keycloak
    restart: always
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: ticket-db
      KC_DB_URL_DATABASE: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - start-dev
    depends_on:
      - ticket-db

volumes:
  ticket-db-data:
  keycloak-data:
