spring:
  application:
    name: data-jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_jpa?createDatabaseIfNotExist=true
    username: root
    password: 1973

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
